version: "3.9"
services:
  myservice:
    image: research:latest
    entrypoint: /newDir/hms.sh
    ports:
      - "80:80"
      - "3306:3306"
    volumes:
      - .:/newDir
      - .\Apps:/var/www/html
    working_dir: /var/www/html